<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
    /**
     * Generator 函数
     * **/
    {
      // 协程的 Generator 函数实现 
      // Generator 函数是协程在 ES6 的实现，最大特点就是可以交出函数的执行权（即暂停执行）。
      function* gen(x) {
        var y = yield x + 2;
        return y;
      }

      var g = gen(1);
      g.next(); // 3
    }

    {
      // Generator 函数的数据交换和错误处理
      // next返回值的 value 属性，是 Generator 函数向外输出数据；next方法还可以接受参数，向 Generator 函数体内输入数据。
      function* gen(x) {
        let y = yield x + 2;
        return y;
      }
      var g = gen(1);
      g.next(); // { value: 3, done: false }
      // 第一个next方法的value属性，返回表达式x + 2的值3。第二个next方法带有参数2，这个参数可以传入 Generator 函数，作为上个阶段异步任务的返回结果，被函数体内的变量y接收。
      // 因此，这一步的value属性，返回的就是2（变量y的值）。
      g.next(2); // { value: 2, done: true }

      // Generator 函数内部还可以部署错误处理代码，捕获函数体外抛出的错误。
      function* gen(x) {
        try {
          var y = yield x + 2;
        } catch (e) {
          console.log(e)
        }
        return y;
      }
      var g = gen(1);
      g.next();
      g.throw("出错了");
      // Generator 函数体外，使用指针对象的throw方法抛出的错误，可以被函数体内的try...catch代码块捕获。这意味着，出错的代码与处理错误的代码，实现时间和空间上的分离，对于异步编程无疑是很重要的。
      // 出错了
    }

    {
      // 异步任务的封装
      // 首先执行 Generator 函数，获取遍历器对象，然后使用next方法（第二行），执行异步任务的第一阶段。由于Fetch模块返回的是一个 Promise 对象，因此要用then方法调用下一个next方法。
      var fetch = require('node-fetch');

      function* gen() {
        var url = 'https://api.github.com/users/github';
        var result = yield fetch(url);
        console.log(result.bio);
      }

      var g = gen();
      var result = g.next();

      result.value.then(function (data) {
        return data.json();
      }).then(function (data) {
        g.next(data);
      });
    }
  </script>
</body>

</html>